# Generated by Django 3.1.1 on 2020-09-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste_bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70)),
                ('poster_name', models.CharField(max_length=300)),
                ('poster', models.TextField()),
                ('poster_type', models.CharField(max_length=10)),
                ('poster_url', models.CharField(max_length=10)),
            ],
        ),
    ]
