# Generated by Django 3.1.1 on 2020-09-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paste_bin',
            new_name='Pastebindb',
        ),
    ]
