# Generated by Django 3.1.2 on 2020-10-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_pastebindb_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastebindb',
            name='user',
        ),
    ]
