# Generated by Django 3.1.1 on 2020-09-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20200922_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebindb',
            name='poster',
            field=models.TextField(blank=True),
        ),
    ]
