# Generated by Django 3.1.1 on 2020-09-23 01:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20200922_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebindb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 23, 1, 27, 29, 517018, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
