# Generated by Django 3.1.1 on 2020-09-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_pastebindb_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebindb',
            name='poster',
            field=models.TextField(),
        ),
    ]
