# Generated by Django 3.1.2 on 2020-10-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postlink',
        ),
        migrations.RemoveField(
            model_name='link',
            name='addressname',
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
